services:
  postgres:
    image: postgres:15
    container_name: app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - app_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  app_data:
