name: Build and Push Docker Image

on:
  push:
    tags:
      # Only trigger on semantic version tags (vX.Y.Z, e.g., v1.0.0, v2.1.3)
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # Also support pre-release tags like v1.0.0-beta.1

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      is_valid: ${{ steps.validate.outputs.is_valid }}
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "version=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $TAG_NAME"

      - name: Validate semantic version format
        id: validate
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          # Validate semantic version pattern (vX.Y.Z or vX.Y.Z-prerelease)
          if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
            echo "is_valid=true" >> $GITHUB_OUTPUT
            echo "✅ Valid semantic version: $VERSION"
          else
            echo "is_valid=false" >> $GITHUB_OUTPUT
            echo "❌ Invalid semantic version format: $VERSION"
            echo "Expected format: vX.Y.Z (e.g., v1.0.0, v2.1.3, v1.0.0-beta.1)"
            exit 1
          fi

  build-and-push:
    needs: validate-tag
    if: needs.validate-tag.outputs.is_valid == 'true'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write # For OIDC token generation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=App Starter Template
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ needs.validate-tag.outputs.version }}
            org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ssZ'}}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Multi-layer caching strategy for optimal performance
          cache-from: |
            type=gha
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Generate build summary
        run: |
          echo "## 🐳 Docker Image Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Build Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ needs.validate-tag.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry**: ${{ env.REGISTRY }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms**: linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Time**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🏷️ Image Tags" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🚀 Usage" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "# Pull the image" >> $GITHUB_STEP_SUMMARY
          echo "docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.validate-tag.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Or pull latest" >> $GITHUB_STEP_SUMMARY
          echo "docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Verify image exists
        run: |
          echo "🔍 Verifying image was pushed successfully..."

          # Wait a moment for the image to be available
          sleep 10

          # Try to pull the image to verify it exists
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.validate-tag.outputs.version }}

          if [ $? -eq 0 ]; then
            echo "✅ Image verification successful!"
            echo "Image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.validate-tag.outputs.version }} is available"
          else
            echo "❌ Image verification failed!"
            exit 1
          fi

      - name: Clean up build cache
        run: |
          echo "🧹 Cleaning up old build cache entries..."

          # Clean up local buildx cache older than 7 days
          docker buildx prune --filter until=168h --force || true

          # Show remaining cache usage
          echo "📊 Remaining cache usage:"
          docker buildx du || true

          echo "✅ Cache cleanup completed"

      - name: Trigger webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL || '' }}
        run: |
          echo "🔗 Checking webhook configuration..."

          # Debug: Check if WEBHOOK_URL is set
          if [ -z "$WEBHOOK_URL" ]; then
            echo "ℹ️ WEBHOOK_URL secret is not configured, skipping webhook trigger"
            echo "To configure: Go to Settings → Secrets and variables → Actions → New repository secret"
            echo "Name: WEBHOOK_URL, Value: your webhook endpoint URL"
            exit 0
          fi

          echo "✅ WEBHOOK_URL is configured"
          echo "🔗 Triggering webhook notification to: ${WEBHOOK_URL:0:20}..."

          # Prepare webhook payload
          PAYLOAD=$(cat <<EOF
          {
            "event": "docker_build_complete",
            "repository": "${{ github.repository }}",
            "version": "${{ needs.validate-tag.outputs.version }}",
            "image": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.validate-tag.outputs.version }}",
            "commit": "${{ github.sha }}",
            "ref": "${{ github.ref }}",
            "actor": "${{ github.actor }}",
            "workflow_run_id": "${{ github.run_id }}",
            "timestamp": "$(date -u '+%Y-%m-%dT%H:%M:%SZ')",
            "tags": $(echo '${{ steps.meta.outputs.tags }}' | jq -R 'split("\n") | map(select(length > 0))')
          }
          EOF
          )

          echo "📦 Payload preview:"
          echo "$PAYLOAD" | jq '.'

          # Send webhook request with verbose output for debugging
          echo "🚀 Sending webhook request..."
          HTTP_STATUS=$(curl -s -o /tmp/webhook_response.txt -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "User-Agent: GitHub-Actions/${{ github.run_id }}" \
            -d "$PAYLOAD" \
            --connect-timeout 30 \
            --max-time 60 \
            "$WEBHOOK_URL")

          echo "📊 Webhook response status: $HTTP_STATUS"

          if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
            echo "✅ Webhook triggered successfully!"
            echo "📄 Response body:"
            cat /tmp/webhook_response.txt
          else
            echo "⚠️ Webhook request failed with status $HTTP_STATUS"
            echo "📄 Response body:"
            cat /tmp/webhook_response.txt
            echo ""
            echo "🔍 Debugging tips:"
            echo "  - Check if the webhook URL is accessible"
            echo "  - Verify the endpoint accepts POST requests with JSON payload"
            echo "  - Check if there are any authentication requirements"
            echo "  - Test the webhook URL manually with curl"
            echo ""
            echo "💡 Manual test command:"
            echo "curl -X POST -H 'Content-Type: application/json' -d '{\"test\":\"message\"}' '$WEBHOOK_URL'"
            echo ""
            echo "Note: Webhook failure does not affect the workflow success"
          fi

  cleanup-old-versions:
    needs: [validate-tag, build-and-push]
    if: needs.build-and-push.result == 'success'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clean up old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Clean up untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Cleanup summary
        run: |
          echo "🧹 Package cleanup completed!"
          echo "✅ Kept latest 5 tagged versions"
          echo "✅ Removed all untagged versions"
          echo "📦 Package: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

  notify-completion:
    needs: [validate-tag, build-and-push, cleanup-old-versions]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        if: needs.build-and-push.result == 'success'
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL || '' }}
        run: |
          echo "🎉 Docker image build and push completed successfully!"
          echo "📦 Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.validate-tag.outputs.version }}"
          echo "🏷️ Also tagged as: latest"
          if [ "${{ needs.cleanup-old-versions.result }}" == "success" ]; then
            echo "🧹 Package cleanup completed successfully"
          else
            echo "⚠️ Package cleanup encountered issues (non-critical)"
          fi
          if [ -n "$WEBHOOK_URL" ]; then
            echo "🔗 Webhook notification was triggered"
          else
            echo "ℹ️ No webhook configured (WEBHOOK_URL secret not set)"
            echo "To configure webhook: Go to Settings → Secrets and variables → Actions → New repository secret"
            echo "Name: WEBHOOK_URL, Value: your webhook endpoint URL"
          fi

      - name: Notify failure
        if: needs.build-and-push.result == 'failure'
        run: |
          echo "❌ Docker image build and push failed!"
          echo "Please check the workflow logs for details."
          echo "Common issues:"
          echo "  - Docker build errors"
          echo "  - Authentication problems"
          echo "  - Network connectivity issues"
          echo "  - Invalid Dockerfile syntax"
          exit 1
